vich_uploader:
    db_driver: orm

    mappings:
       avatar:
           uri_prefix: /assets/uploads/avatar
           upload_destination: '%kernel.project_dir%/public/assets/uploads/avatar'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
